import type { Metadata } from "next";
import "./globals.css";
import { ViewTransitions } from "next-view-transitions";

import { pretendard } from "@/ui/font";


export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body className={`${pretendard.variable}`}>
        <ViewTransitions>{children}</ViewTransitions>
      </body>
    </html>
  );
}
